spring:
  jpa:
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: none
      show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  main:
    banner-mode: console
  liquibase:
    change-log: classpath:db/changeLogs.xml
    enabled: 'true'
  datasource:
    password: '123'
    username: postgres
    url: jdbc:postgresql://localhost:5432/Eshop
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: 'true'
stripe:
  enabled: 'false'
server:
  error:
    include-binding-errors: always
    include-message: always